#!/bin/sh

# Create /var/run/motdgen if missing
rundir=/var/run/motdgen
if [ ! -f "$rundir" ]; then
    mkdir $rundir
fi

if [ -f /run/ostree-booted ]; then
    rpm-ostree upgrade --check --preview > /var/run/motdgen/rpmostree_updateinfo.out
    updates=$(cat /var/run/motdgen/rpmostree_updateinfo.out | grep "^\!" | wc -l)
    new=$(cat /var/run/motdgen/rpmostree_updateinfo.out | grep "^+" | wc -l)

    if [ $updates -ne 0 ] || [ $new -ne 0 ]; then
        echo "Updates available: $updates update(s), $new install(s)." > /var/run/motdgen/updateinfo.txt
    else
        echo "No updates available." > /var/run/motdgen/updateinfo.txt
    fi
else
    dnf -qC updateinfo > /var/run/motdgen/updateinfo.txt
fi
