# /var/run/motdgen/updateinfo.txt is generated by motdgen-cache-updateinfo
# , which gets triggered periodically by systemd.timer and post dnf
# transactions
path=/var/run/motdgen/updateinfo.txt

if [ -f "$path" ]; then
    cat $path
else
    echo "Update info not available yet!"
fi
